export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAILURE = 'ORDER_SUBMIT_FAILURE';
export const DELETE_ORDER_NUMBER = 'DELETE_ORDER_NUMBER';
export const SET_ORDER_MODAL_VISIBLE = 'SET_ORDER_MODAL_VISIBLE';
export const SET_ORDER_MODAL_INVISIBLE = 'SET_ORDER_MODAL_INVISIBLE'